server {
    listen 80;
    server_name laradocker.trigger.ltd;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name laradocker.trigger.ltd;

    root /var/www/laradocker09.01.26/public;
    index index.php index.html;

    ssl_certificate /etc/letsencrypt/live/laradocker.trigger.ltd/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/laradocker.trigger.ltd/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9001;  # теперь хост видит PHP-FPM
        fastcgi_param SCRIPT_FILENAME /var/www/laradocker09.01.26/public$fastcgi_script_name;
        
    }

    location ~ /\.ht {
        deny all;
    }

    client_max_body_size 100M;
}