# Redirect all HTTP to HTTPS
#server {
#   listen 80;
#   server_name laradocker.trigger.ltd;
#   return 301 https://$host$request_uri;
#}

# HTTPS server
server {
    listen 443 ssl http2;
    server_name laradocker.trigger.ltd;

    ssl_certificate /etc/letsencrypt/live/laradocker.trigger.ltd/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/laradocker.trigger.ltd/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    root /var/www/public;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass laradocker_app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTPS on;
    }

    # Security: hide .env and hidden files
    location ~ /\. {
        deny all;
    }
}
