name: Laravel Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Переходим в папку проекта на сервере
            cd /var/www/laradocker09.01.26

            # Обновляем код с GitHub
            git pull origin main

            # Пересобираем контейнеры
            docker compose -f docker-compose.prod.yml down
            docker compose -f docker-compose.prod.yml up -d --build

            # Устанавливаем зависимости Laravel внутри контейнера app
            docker compose -f docker-compose.prod.yml run --rm -w /var/www/laradocker09.01.26 app composer install --no-interaction --optimize-autoloader

            # Прогоняем миграции
            docker compose -f docker-compose.prod.yml run --rm -w /var/www/laradocker09.01.26 app php artisan migrate --force

            # Кешируем конфигурацию Laravel
            docker compose -f docker-compose.prod.yml run --rm -w /var/www/laradocker09.01.26 app php artisan config:cache